### ISSUE TITLE
Baseline Project - Standards and Specifications - Protocol CORE Specification

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-roadmap#107]
**#Objective**
Define the core semantics, components and facilities of the Baseline Protocol.

**#Components**
https://docs.baseline-protocol.org/baseline-protocol/components
https://github.com/ethereum-oasis/baseline/tree/init-core

Microservices-based architecture
Docker containers : Baseline Containers, Provide Containers, Unibright Proxy https://github.com/ethereum-oasis/baseline/tree/init-core/examples/erp-connector-proxy
Baseline API
Messaging Service
Zero Knowledge Service
Smart Contract Management Service

**Comment by Consianimis** [comment]
Questions:
1.Conformance clauses - Confirm that [RFC 2119] is recommended and not [ISO/IEC Directives] ?
2. What are the top 3 mistakes in writing specifications such as business process descriptions or reference models that are not meant to be implemented in computer code ?
3. Are there different types of implementations that could claim comformance to the baseline protocol specifications or is the focus on "baseline server" implementation ?
4. Do we need to specify what type of protocol Baseline is - Is it similar to a (tunneling) communication protocol but on blockchain or closer to a process automation protocol ?
5. Do Baseline protocol specs qualify for testing/do we need to think about conformance testing i.e. test assertions requiredDo Baseline protocol specs qualify for testing/do we need to think about conformance testing i.e. test assertions required ?
4. Do we need to specify what type of protocol Baseline is - Is it similar to a (tunneling) communication protocol but on blockchain or closer to a process automation protocol ?
5. Are there different types of implementations that could claim comformance to the baseline protocol specifications or is the focus on "baseline server" implementation ?

**Comment by chaals** [comment]
Good Questions.
1. IMHO RFC 2119 language should be used, and sparingly (only the things you need). If we are going to use an RFC 2119 term, make sure it is only ever used in the RFC 2119 sense in the spec.
2. I'm not sure I understand this question
3. The spec should be testable - and if you pass the tests, you should be set up to make baselining work.
4. We don't need to answer in these terms. We describe how it actually works, and then we can work out the most helpful explanations of what it is like later.
5. I don't know, but when we write down who in the ecosystem needs to do what to make it work, we will have the answers.

**Comment by Consianimis** [comment]
Please refer to https://github.com/ethereum-oasis/baseline/tree/master/docs/specs.
