### ISSUE TITLE
Messaging Services

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#11]

**Comment by humbitious** [comment]
Hey guys, this is the placeholder for containing the work around messaging services, which I know we have incorporated into Init-Core.  @kthomas , let's see if we can cross-ref the proper issues here. Would like to do an update on this on next TSC.

**Comment by kthomas** [comment]
Closing this as it has been covered in other issues and is represented within the upcoming init-core release.
