### ISSUE TITLE
TSC Agenda and Minutes: September 10, 2020

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#112]
Agenda:

[5min]: Welcome new attendees, request for additions/modifications to agenda.

[10min]: Review Maintainer status -- new Maintainers, any issues to resolve

[15min]: Review of Roadmap and completed/near-completed projects

[15min]: Discussion/retrospective on community practices

TSC Meetings Recorded and posted for public on Baseline Protocol YouTube Channel

**Comment by bitwiseguy** [comment]
# Maintainers meeting
Date: 2020.08.31
Maintainer Attendees: Sam Stokes, Kyle Thomas, Brian Chamberlian, Tomasz Stanczak
Guest Attendees: John Wolpert

## Minutes
* Vote: to remove one inactive maintainer and add one new maintainer
    * we do not have a quorum for this meeting, so will conduct the vote via github PR approvals
* Docs: Jory still researching gitbook alternative
* Preliminary discussion: should we add specifications contributors to maintainers team
    * Final decision tabled for a future maintainer meeting so that we can get everyone’s input
* Release v0.1: Concern around size of init-core branch
    * Future PRs should be smaller because they will ideally build off of the existing baseline core packages
* Upcoming work (new issues to create and put on roadmap:):
    * modify existing demos to import+use core baseline packages
    * build core/persistence package work

**Comment by humbitious** [comment]
# Minutes from TSC Meeting
11am US-ET September 10, 2020

TSC Attendees: John Wolpert (chair), Eric Bravick, Hudson Jameson, Stefan Schmidt, Kyle Thomas, Nate McKervey, Conor Svensson.

Chair proposed merging the TSC meeting with the SSC meeting and using the existing SSC meeting, normally held on Mondays at 11am US-ET.

## To be Proposed to the PGB for ratification on September 23, 2020 ( @jorydotcom )
1. The SSC shall be renamed to SC (Steering Committee). 

2. The TSC shall retain its name (Technical Steering Committee) and remain the governing 11 elected members with no changes to the current charter ( https://docs.baseline-protocol.org/community/governance). 

3. The team forming currently to develop the official Baseline Protocol Standards content shall be named the TC (Technical Committee), and normal meetings of the TC shall be held bi-weekly (or as the team decides going forward), starting in the current timeslot of the TSC. This will bring us into alignment with the normal OASIS standards process, which refers to the standards writers as the TC.  (The difference for us being that we also now have a TSC, which is the official governing group of 11 elected members holding decision-making rights for both open source and standards development.)

4. The TC has only one restriction (which shall be added to the charter): Only individuals that have signed the iCLA (and for companies, the eCLA) may participate in meetings of the TC or contribute directly to the standards documents. 

[Note: The reason for this involves the need to comply with OASIS rules and general practices with regard to, for example, the assurance of intellectual property non-entanglement (part of the CLA). TC members may also be TSC members, and this is encouraged, but it is important to ensure that all TSC members have signed the CLA, particularly if they contribute to the Standards docs. The easiest way to do this is to have all TSC and TC members do at least one pull request and have it merged to master in the /baseline repo.]

5. The TC will utilize only .md editing within, for now, the current github.com/ethereum-oasis/baseline repo. And some or all TC members may be designated as Maintainers, so that we do not need to create and manage a new repo and Maintainer org for the Standards work. This will give Standards writers the ability to approve merging pull requests to the Master (main) branch of the repo, as any other Maintainer can do.

[Note: While it is possible that the combination of standards maintainers and code maintainers in the same group with the same access to the repo functions may result in problems of non-technical standards people approving technical contributions under the multi-reviewer approval process (currently 3 Maintainer approvers), it is asserted that this is manageable, problem incidents can be quickly identified, and remedies are already written into the charter and the Maintainer guidelines. We can change this to add a new standards repo and maintainer org in future if this becomes a problem.]

No dissent on the proposal was recorded from any of the seven attending TSC members. At least one of the remaining TSC members not in attendance should indicate assent/dissent in a comment to this Issue.  (@breakpointer @skarred14 @JohannEid)

---
## Elections: 

The Chair requested approval to propose a change to the charter in order to allow for a slip of the election process to the 15th of October, if necessary. This may turn out to be unnecessary, but it may be important to get a little extra time to onboard incoming sponsors and contributors and to ensure that candidates have been vetted and have had a chance to make their case to the contributors for voting in the 2020/21 11 member TSC body.  The Chair will determine the need for this extension by no later than September 18.  No dissent on the proposal was recorded from any of the seven attending TSC members. At least one of the remaining TSC members not in attendance should indicate assent/dissent in a comment to this Issue.  (@breakpointer @skarred14 @JohannEid)

A strong call to action was made to all TSC members to get people that should be voting into the Github contributor list.

Hudson Jameson offered this guide to contribution for consideration, with possible additions to the baseline protocol docs on how to contribute: https://github.com/ethereumbook/ethereumbook/blob/develop/CONTRIBUTING.md#license-and-attribution
This may help with managing standards work.

## Additional discussions:

Kyle Thomas floated the idea of reducing the TSC term to 6 months. The fact that the TSC charter is allowed to drop to 7 or 9 members was also discussed. Dan Burnett also floated the idea of doing overlapping terms (e.g., half of members voted in September for a year and other half in March) for the TSC.

---
Sketch of the repo and organization of code into /core, /bri-(n), etc and the docs and standards into a separate folder in the same repo.
![image](https://user-images.githubusercontent.com/1388686/93024032-1f3ff580-f5c1-11ea-8dd8-b65c5bb0d6bc.png)
