### ISSUE TITLE
Steering Committee Meeting Agenda and Minutes -- September 28

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#119]
## The bi-weekly Steering Committee Meeting. 

Minutes from Maintainer and Technical (standards) Committee meetings from the 2 weeks leading up to this meeting should be placed in comments so that the community can review, discuss and memorialize.

## Agenda:

[30min]: TSC Candidates Review and Voting Start

[20min]: Roadmap Discussion

[10min]: Regular business

Meetings Recorded and posted for public on Baseline Protocol YouTube Channel

**Comment by bitwiseguy** [comment]
# Maintainers meeting minutes
Date: 2020.09.21
Maintainer Attendees: Sam Stokes, Kyle Thomas, Brian Chamberlain, Kartheek Solipuram, Tomasz Stanczak
Guest Attendees: John Wolpert, David Mechler, Tim Beiko
* Docs: Jory (OASIS) still researching gitbook alternative
* Active work
    * Stabilizing bri-1 test suite: PR #227
    * Updating radish34 to use latest version of zokrates
    * Building generic “createDocument” zk circuit to replace no-op circuit currently used by bri-1
* Upcoming work:
    * build core/persistence package
    * Midnight Friday gmt get voter registration
        * must have PR merged to be able to vote
