### ISSUE TITLE
Steering Committee Meeting Agenda and Minutes -- October 12, 2020

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#120]
## The bi-weekly Steering Committee Meeting. 

Minutes from Maintainer and Technical (standards) Committee meetings from the 2 weeks leading up to this meeting should be placed in comments so that the community can review, discuss and memorialize.

## Agenda:

[15min]: Technical Steering Committee addresses any outstanding Maintainer issues or votes

[5min]: Celebrate momentum -- Recent announcements + Growth metrics

[20min]: Discuss what should be the one or two highlights of community work for the next two weeks

[15min]: Regular business

Meetings Recorded and posted for public on Baseline Protocol YouTube Channel

**Comment by bitwiseguy** [comment]
# Maintainers meeting minutes
Date: 2020.10.05
Maintainer Attendees: Sam Stokes, Kyle Thomas, Kartheek Solipuram, Tomasz Stanczak, George Spasov
Guest Attendees: John Wolpert
* Proposals
    * maintain backlog of top 3 most important next capabilities/tasks
        * github issues with “maintainers” or “core” tag
        * focus on “core” packages
        * 2 week sprints?
    * record maintainers meetings
    * move maintainers meeting one hour earlier
* Sprint items:
    * list of topics for Baseline design summit
    * documentation for core packages: types
    * OpsChain meeting with maintainers/TSC members to review tech. architeture of core
    * add protocol buffers to messaging/types
        * talk to Alex Kritikos
    * Make phonebook implementable: core should support OrgRegistry/Phonebook
        * poll the TSC for roadmap of Baseline protocol and extrapolate from there
    * Invite Anais to maintainers meetings: add her as maintainer or guest

**Comment by humbitious** [comment]
Lead brainstorming on Maintiainer issues @Perseverance
