### ISSUE TITLE
Steering Committee Meeting Agenda and Minutes -- October 26, 2020

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#121]
## The bi-weekly Steering Committee Meeting. 

Minutes from Maintainer and Technical (standards) Committee meetings from the 2 weeks leading up to this meeting should be placed in comments so that the community can review, discuss and memorialize.

## Agenda:

[5min]: Technical Steering Committee addresses any outstanding Maintainer issues or votes

[30min]: Review and prioritize November Summit tracks...and review overall plans for the Summit

[20min]: ZK performance review @gleim 

Meetings Recorded and posted for public on Baseline Protocol YouTube Channel

**Comment by gleim** [comment]
ConsenSys Health will be presenting a ZK performance benchmarking tool and white paper to support and improve production-readiness assessment capabilities for ZK circuits.  ~20 minutes is expected to be the presentation length [likely inclusive of Q&A].

**Comment by bitwiseguy** [comment]
# Maintainers meeting minutes
Date: 2020.10.19
Maintainer Attendees: Sam Stokes, Kartheek Solipuram, Tomasz Stanczak, George Spasov
Guest Attendees: John Wolpert
* Baseline Summit planning
    * Proposal: have a champion for each task
    * Containerize api service
    * Do we need to define baseline API gateway REST server as single target for ERP systems to send all baseline requests?
    * Should we deliver tools to verify an implementation complies to specification?
        * rosetta cli tool can do this: https://www.rosetta-api.org/
        * Should we have a “baseline API gateway” service? Or multiple endpoints inside a baseline system are directly accessible?
* Will send out Google forms voting ballot to add Anais Ofranc as maintainer
* Working on generic shield contract that then connects to a MerkleTree. Current bri-1 implementation deploys a MerkleTree.sol contract but no Shield contract with on-chain proof verification
