### ISSUE TITLE
Standards and Specifications Meeting Minutes: October 22, 2020

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-roadmap#130]
# Standards and Specifications meeting
Date: 2020.10.22

## Minutes 
* Discussed
    * [5mins] Follow up on October 08th closed and open items.
    *[35mins] Security Considerations requirements category
    *[20 mins] Conformance requirements category
* Next steps:
    Who/What: Kartheek Solipuram - Definition of shielding mechanism.
    Who/What: Andreas Freund - Circuit break, Portability & Interoperability .
    Who/What: Chaals/Andreas - Standard purpose and benefits
    Who/What: Daniel/Anais - Standard 2 - API & Data Model

**Comment by Therecanbeonlyone1969** [comment]
Standard Purpose & Benefit:
The Baseline Protocol Standard is aimed to provide a coherent, concise, and understandable definition of what the Baseline Protocol is and provide a set of concise, understandable, and, most importantly, readily testable requirements any technology implementer can follow in building a standard-compliant product.

This will allow implementers to prove to their customers that their products follow rigorous enterprise-grade standards in security, privacy, availability, reliability, and scalability.

Definition of a Baseline Circuit Breaker:
The ability of a Baseline user to immediately cease all their active business processes within a Baseline implementation, and, if required, exit/leave a Baseline implementation with all their data without any 3rd party being able to prevent the exit.

Definition of Portability:
The ability of a Baseline user to migrate and re-baseline their existing business processes and data from one Baseline implementation to another Baseline implementation without any 3rd party being able to prevent the migration.

Definition of Interoperability:
The ability of a baseline user operating business processes on Baseline implementation A to instantiate and operate one or more business processes with one or more baseline user on Baseline Implementation B without the Baseline user on either Baseline Implementation A or B having to know anything of the other Baseline implementation.
