### ISSUE TITLE
Blockchain Client Support for Baselining

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#143]
## Project Description
This master epic will contain issues and projects involved in adding more blockchain clients that can support baselining.

## Impact on the Baseline Community

This will enhance the potential user base of the Baseline Protocol. As it currently stands, users of the baseline protocol make use of Nethermind (which is an awesome client btw), however choice is important and we'd like to see Baseline support in other enterprise focussed clients such as Hyperledger Besu.

In addition to the client, we'd like to provide support for other development platforms such as the Java Virtual Machine (JVM) and the .NET framework - currently the Baseline implementation is written in TypeScript (JavaScript).

The JVM is very widely used in enterprise, and by supporting a native JVM implementation for Baseline, it is likely to open more opportunities for organisations to work with the protocol.

## Acceptance criteria and must have scope
The initial goal is to support a JVM Baseline implementation with Web3j and Hyperledger Besu. However, there are a number of core components to the protocol which will need to be potentially reimplemented, which is likely to take time. This includes support for the following:

- Core contracts
- Zokrates privacy circuits
- API implementation
- Organisation registry
- Messaging (NATS)
- Persistance
- Privacy
- Example project

## Timeline
3-6 months.

---

[Background](https://help.zenhub.com/support/solutions/articles/43000010341) on Epics, Issues, Checkboxes (aka, Epics, Stories, Tasks)

After you start breaking this master epic up into a set of Issues (sub-epics, stories, tasks, etc), you might consider creating a Project in Github to make it easy for your group to have a single Kanban board for just this work. The Github projects tab in any given repo will allow only Issues from that repo, but if you create one [here](https://github.com/orgs/ethereum-oasis/projects), you will be able to set up a project that can compose Issues from any of the baseline repos, including the core /baseline repo and the planning /baseline-roadmap repo.

**Comment by bitwiseguy** [comment]
The [commit-mgr](https://github.com/ethereum-oasis/baseline/tree/master/examples/bri-2/commit-mgr) Ethereum client extension makes all clients "baseline-compatible". Tested and working with the following clients types:
* ganache
* besu (private network)
* Infura (classic API)
* Infura gas service (ITX)
