### ISSUE TITLE
Hyperledger Besu support for Baseline

### ISSUE THREAD

**Issue by conor10** [ethereum-oasis/baseline-roadmap#145]
### Challenge Description 

In its current implementation, Baseline uses [Nethermind](https://docs.nethermind.io/nethermind/enterprise/baseline) for a couple of core pieces of functionality:

- Transacting with the Ethereum network
- Off-chain Merkle tree persistence 

This issue is to add similar Baseline support to [Hyperledger Besu](https://besu.hyperledger.org/). This can be done either by directly extending the Hyperledger Besu JSON RPC APIs, by using the [Besu Plugins API](https://besu.hyperledger.org/en/stable/Concepts/Plugins/), or a combination of both.

The following resources can be used to support the implementation:

- Plugins in [Hyperledger Besu](https://besu.hyperledger.org/en/stable/Concepts/Plugins/)
- [Baseline JSON-RPC API](https://github.com/ethereum-oasis/baseline/blob/master/docs/specs/api/baseline-api-v1.0-psd01.md#3-ibaselinerpc)
- [Nethermind Baseline docs](https://docs.nethermind.io/nethermind/enterprise/baseline)

In order to demonstrate successful implementation of this functionality, a [sample project](https://github.com/ethereum-oasis/baseline/tree/master/examples) should be created using Hyperledger Besu.

### Submission Requirements 

* Before beginning to implement, please reach out to our team in the #besu-contributors channel of the Hyperledger Chat (https://chat.hyperledger.org);
* The implementation should conform to the [Baseline specification ](https://github.com/ethereum-oasis/baseline/blob/master/docs/specs/api/baseline-api-v1.0-psd01.md#3-ibaselinerpc);
* The implementation should be validated by creating a Baseline [sample project](https://github.com/ethereum-oasis/baseline/tree/master/examples);
* The implementation should have unit and acceptance tests as judged appropriate;
* Any addition to the Hyperledger Besu codebase must comply with the [Contribution Guidelines](https://github.com/hyperledger/besu/blob/master/CONTRIBUTING.md);
* Any new library or dependency must be Apache 2.0 friendly;

### Judging Criteria

The bounty will be awarded to the best submission based on the quality of the implementation, testing, documentation (e.g. PR description, code comments, javadocs, etc.), and compliance with the Submission Requirements above, according to the Besu & Baseline maintainers.

### Winner Announcement Date: TBA

**Comment by conor10** [comment]
According to discussions with @bitwiseguy during the Baseline Summit, work has already started on this item in the form of a Baseline relay. It would be great to learn more - @timbeiko and @davemec.

**Comment by timbeiko** [comment]
@conor10 yes, it has! The relay currently works with Ganache, and we'll need to test it with Besu. We suspect we'll have some small modifications to do as part of that testing, but it should not be too big. We can post an update here once it's done :-)

**Comment by humbitious** [comment]
@bitwiseguy , I'd say that perhaps much of this is "done" when your pull request is merged for commitment manager and blockchain switcher.  Should we connect your pr to this and mark complete when merged?

**Comment by humbitious** [comment]
@conor10 I'm thinking that we can move this to backlog and opt for the "Blockchain Switcher" in #162 for the hackathon.  What do you think?

**Comment by bitwiseguy** [comment]
Besu is now "baseline-enabled" by the [commit-mgr](https://github.com/ethereum-oasis/baseline/tree/master/examples/bri-2/commit-mgr) Ethereum client extension
