### ISSUE TITLE
Review and Improve IBaselineRPC

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-roadmap#152]
## Problem Statement

The draft API spec states that the deploy function of the IBaselineRPC interface is a requirement. However it is implementation specific as it is used to deploy a shield contract. Shield contract is not a requirement of the CORE protocol spec.
During the summit, it was discussed that the deploy function has been either replaced or complemented by another function.
There needs to be a review of the IBaselineRPC interface to ensure that all implementation specific items are identified and discussed. The draft API spec needs to be updated accordingly.

**Comment by bitwiseguy** [comment]
This PR makes significant changes and improvements to the IBaselineRPC interface: https://github.com/ethereum-oasis/baseline/pull/259

**Comment by Consianimis** [comment]
No longer needed. Closing the issue.
