### ISSUE TITLE
Add support for snarkjs to the Baseline core privacy package.

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-roadmap#153]
## Challenge Description

The only zkSNARK frontend toolbox currently supported by the Baseline core privacy package is ZoKrates.
The challenge is to enhance the Baseline core privacy package to provide support for snarkjs by improving on the existing interfaces: IZKSnarkCircuitProvider and IZKSnarkCompilationArtifacts.
This stub was created for illustrative purposes : https://github.com/ethereum-oasis/baseline/tree/snarkjs-wip/core/privacy/src but you are welcome to use it as a starting point if you wish to do so.

## Challenge Requirements

The functional requirements of this challenge are:

<table>
<tr>
    <th>Requirement ID</th>
    <th>Requirement</th>
    <th>Nb of Points</th>
  </tr>
  <tr>
    <td>ZK01</td>
    <td>The solution must enable the construction of an arithmeric circuit by an Initiator .</td>
    <td>20 pts </td>
  </tr>
  <tr>
    <td>ZK02</td>
    <td>The solution must enable the Initiator to deploy a trusted setup using snarkjs.</td>
    <td>20 pts </td>
  </tr>
  <tr>
    <td>ZK03</td>
    <td>The solution must allow a Prover to run the circuit (i.e. calculate the witness) and to generate snark proofs with snarkjs.</td>
    <td>20 pts </td>
  </tr>
  <tr>
    <td>ZK04</td>
    <td>The solution must provide the mechanisms to verify snark proofs on-chain.</td>
    <td>20 pts </td>
  </tr>
  <tr>
    <td>ZK05</td>
    <td> An architecture/flow diagram of the solution must be provided.</td>
    <td>5 pts </td>
  </tr>
</table>

## Submission Requirements

A valid submission delivers on all requirements from ZK01 to ZK05 Each requirement fullfilled can earn up to 20 points  broken down as below:

<table>
<tr>
<td> Code + Unit tests provided 
</td>
<td>10 pts
</td>
</tr>
<tr>
<td> Documentation of interfaces and methods provided
</td>
<td>5 pts
</td>
</tr>
<tr>
<td> Code quality (i.e. follows best practices)
</td>
<td>5 pts
</td>
</tr>
</table>

## Judging Criteria

If multiple valid submissions are received and if they score equally, the winning team will be the one with the highest number of votes from the judges.

## Related Documentation

Baseline core privacy package: https://github.com/ethereum-oasis/baseline/tree/master/core/privacy
Snarkjs documentation: https://github.com/iden3/snarkjs and https://www.npmjs.com/package/snarkjs
For any questions visit the Slack channel:  [#gitcoin-hackathon-2020](https://app.slack.com/client/TSX2XPFSN/C01EUPPGX18)

**Comment by kthomas** [comment]
FYI this stub was created for illustrative purposes if someone wants to pick it up and take it the distance: https://github.com/ethereum-oasis/baseline/tree/snarkjs-wip
