### ISSUE TITLE
Baseline Scaling Requirements from the 2020 Baseline Summit

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [ethereum-oasis/baseline-roadmap#156]
Key Question #1: Transaction scaling vs. transaction costs vs. network impact vs. security -- How does Baseline scaling impact permissionless network throughput and transaction pricing

Key Question #2: Determinism vs. parallelism -- how to ensure correct state transitions in a parallel processing environment?

Key Question #3: Data availability vs. throughput vs. privacy -- what are the requirements and tradeoffs?

FR = Functional Requirement

NFR = Non-Functional Requirement

Key Question | Nr. | Architecture Layer | Element | Type | Requirement |
|-- | -- | -- | -- | -- | -- |
#1 | 1 | Interfaces & Applications | API Gateway | NFR | API gateway must support high-operational throughput -- at least 1000 tps
#1 | 2 | Middleware | Identities/Accounts/Workgroups | NFR | Operator may employ a centralized solution
#1 | 3 | Middleware | Identities/Accounts/Workgroups | FR | Operator must synchronize workgroup entities and their account to the Baseline Global Phone book
#1 | 4 | Middleware | Identities/Accounts/Workgroups | FR | Operator may add additional operator specific metadata to synchronized records
#1 | 5 | Middleware | Identities/Accounts/Workgroups | FR | Operator must not have the ability to change, update or delete Baseline global phonebook records
#1 | 6 | Middleware | Messaging | NFR | In the single operator model, an operator may use centralized messaging solutions that meet at least the scaling requirements for the API gateway
#1 | 7 | Middleware | Messaging | NFR | In the network operator model, an Operator must be able to support more than 1 messaging protocol
#1 | 8 | Middleware | Messaging | NFR | In the network operator model, messages must be replicable between network participants with low-latency and throughput meeting at least API gateway throughput requirements
#1 | 9 | Middleware | Messaging | NFR | Identities of the message sender and recipient must be based on validated identifiers from the Baseline Global Phone book
#1 | 10 | Processing | Virtual State Machine | FR | A Baseline Virtual State Machine needs to be able to perform general computations for state transitions from State A to State B
#1 | 11 | Processing | Virtual State Machine | NFR | If the Operator is allowed to see any type of transaction data, the operator may utilize a non-privacy preserving scaling solution such as sidechain, rollup or statechannel
#3 | 12 | Processing | Storage | NFR | If the Operator is allowed to see any type of transaction data and the data is to be used in a tokenization event on L1/public DLT, the operator must  the operator must allow for the availability of all token related data on the L1/public DLT layer within an L1 finalization time of less than 1 hour
#3 | 13 | Processing | Storage | NFR | If the Operator is allowed to see any type of transaction data and the transaction data will not be used in a tokenization event or in a tokenization event where the token does not exist on an L1/Public DLT, the operator may utilize a non-privacy preserving scaling solution for offchain computation with only minimal cryptographic, privacy-preserving data on L1/public DLT such as a content-addressable hash
#1 | 14 | Processing | Virtual State Machine | NFR | If the Operator is not allowed to see any type of transaction data, the operator must utilize only a privacy-preserving scaling solution
#1 | 15 | Processing | Virtual State Machine | NFR | If the Operator is not allowed to see any type of transaction data, the operator may utilize an anonymity preserving scaling solution
#3 | 16 | Processing | Storage | NFR | If the Operator is not allowed to see any type of transaction data and the transaction data will not be used in a tokenization event or in a tokenization event where the token does not exist on an L1/Public DLT, the operator must utilize only a privacy-preserving scaling solution for offchain computation with only minimal cryptographic data on L1/public DLT such as a content-addressable hash
#3 | 17 | Processing | Storage | NFR | If the Operator is not allowed to see any type of transaction data then and the data is to be used in a tokenization event on an L1/Public DLT, the operator must allow for availability of all token related data on the L1/public DLT layer within an L1 finalization time of less than 1 hour
#1 | 18 | Public DLT | Security | NFR | Baseline Smart Contract system must have defense mechanisms against transactions spamming. </br><br></br>Note: At a minimum, a known and validated set of operators with write access and a large operator bond combined with a limit on the number of transaction per block a Baseline smart contract will allow as a slashing condition to disincentivize spamming
#2 | 19 | Middleware | Messaging | NFR | A Baseline Messaging protocol must ensure message linear sequencing
#2 | 20 | Middleware | Messaging | NFR | A Baseline Messaging protocol must ensure a high-level of message completeness (99.99%) within an operational processing window
#2 | 21 | Overall Stack | All | NFR | An operator must avoid state dependencies across Baseline implementations or non-interoperable workflows due to technology constraints.</br><br></br>Note: If there is a state dependency between baseline transactions on two or more different baseline implementations such as an MSA shared between two  baseline workflows on two different stacks, there is no way to ensure consistency of both offchain and onchain transactions
#2 | 22 | Processing | Virtual State Machine | FR | An operator should support multiple deterministic execution frameworks
#2 | 23 | Processing | Virtual State Machine | FR | An operator should not allow for cross execution framework state dependencies at the beginning or during the execution of a workflow (instance)</br><br></br>Note: There is no direct way to prove the correctness of state from one workflow in another workflow across different execution frameworks because they "do not speak the same language". It would require a translation relay which introduces an additional attack surface and workflow dependency that counterparties cannot control.
#2 | 24 | Processing | Transactions | FR | Each transaction must have the following identifiers by identifier type:<ul><li>Workflow ID (UID)</li><li>Workflow Instance ID (UUID) -> must be connected to Workflow ID</li><li>Workflow Step ID (UID) -> must be connected to workflow ID</li><li>Workflow Instance Step ID (UUID) -> must be connected to Workflow instance ID</li></ul>
#2 | 25 | Processing | Transactions | FR | Each transaction must be associated with a deterministic nonce
#2 | 26 | Processing | Account | FR | A deterministic nonce should be associated with an AccountNote: There are separate account requirements. <ul><li>An account must have an account number/address (GUUID)</li><li>An account must have at least one account owner</li><li>An account may have more than one account owner</li><li>An account may be associated with the state of a workflow</li><li>An account may have one or more token balances</li><li>Account ownership must be cryptographically provable</li><li>A transaction from an account changes the state of the account</li></ul>
#2 | 27 | Processing | Virtual State Machine | FR | Transactions for the same workflow instance must be deterministically ordered
#2 | 28 | Processing | Virtual State Machine | FR | A transaction referring to an account must fail if <ul><li>The transaction nonce,n, is not equal to the account nonce plus 1, N+1.</li><li>The cryptographic signature of the account owner(s) on the transaction cannot be verified</li><li>The transaction does not have the correct Workflow ID, Workflow Instance ID, Workflow Step ID, Workflow Isnatnce Step ID</li><li>The transaction is not well-formed based on the requirements of the chosen execution framework</li></ul>
#2 | 29 | Processing | Transactions | FR | The unique IDs on a transaction should be generated by the transaction originator
#2 | 30 | Processing | Transactions | FR | The unique IDs on a transaction may be generated by the Baseline Operator or Baseline Operator Network
#2 | 31 | Processing | Consensus | FR | If there is a baseline operator network to execute and confirm transactions, the consensus algorithm employed must have a time to finality << than the time to finality of the underlying L1/public DLT
#2 | 32 | Processing | Consensus | FR | If there is a baseline operator network, the consensus algorithm may only order the transactions based on the UIDs on the transactions</br><br></br>Note: This would allow different operators in the network to utilize different execution frameworks
#2 | 33 | Processing | Consensus | FR | If there is a baseline operator network and it chooses consensus on the execution of a transaction, there must be a consensus algorithm on both the order and the correct execution of transactions
#2 | 34 | Processing | Consensus | FR | If there is a baseline operator network and it chooses consensus on the execution of a transaction, the network must use a common execution framework</br><br></br>Note: If more than one execution framework were chosen, no consensus could be reached on the outcome of a transaction because the state representation is execution framework dependent e.g. Ethereum account state vs. a zk-proof of account state
#3 | 35 | Processing | Entire Stack | NFR | Baseline Scaling solutions must have at least the same security assurances as the L1/Public DLT
#3 | 36 | Processing | Virtual State Machine | NFR | The cryptographic primitives of a baseline scaling solution must have been audited by a 3rd party
#3 | 37 | Processing | Virtual State Machine | NFR | The cryptographic primitives of a baseline scaling solution should have passed the NIST Cryptographic Module Verification Program (CMVP)
#3 | 38 | Processing | Storage | FR | If required, a baseline user must be able to access baseline offchain data from an operator (network) at all times
#3 | 39 | Processing | Storage | FR | A baseline user must not have write privileges to baseline offchain data unless the user is also a baseline operator (single or in a network)
#3 | 40 | Processing | Storage | FR | Baseline offchain data storage must be append-only if it is configured as a P2P or Master-Master replication system

2020 Baseline Summit: Scaling Baseline Track Mindmaps:
[https://drive.google.com/file/d/1qwcNRIb4Ywdby9eFPPvvrHsnn3RGtnWa/view?usp=sharing](url)

2020 Baseline Summit: Scaling Baseline Requirements and Scaling Solution Evaluation Criteria:
[https://docs.google.com/spreadsheets/d/1IDZ4ZX2huVRFT1ogVSgMRf1oEdNXd88pRXLsczhUHZE/edit?usp=sharing](url)

**Comment by Consianimis** [comment]
Added to the Baseline Protocol - Requirements Mastersheet. Issue can be closed.

**Comment by Consianimis** [comment]
Is this a duplicate of https://github.com/ethereum-oasis/baseline-roadmap/issues/174 ?
