### ISSUE TITLE
Baseline Specifications: Baseline Workflow/Workflow-Step naming

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [ethereum-oasis/baseline-roadmap#165]
Initial List of Baseline Workflows and Worksteps:

**Baseline Identity Management:**

Assumptions: 
- Baseline utilizes W3C DIDs and VCs
- Each Baseline user already has a DID around which a Baseline Identity is created
- DIDs and associated public keys are managed by the user
- DIDs and associated keys are anchored on the same public DLT as the Baseline stack operates on

1.     RequestIdentity
2.	CreateIdentity
3.	RegisterIdentity
4.	GetRegisteredIdentity
5.	RequestUpdateIdentity
6.	UpdateIdentity
7.	RevokeIdentity
8.	RequestIdentityPresentation

** User Management **

1. CreateUser
2. UpdateUser
3. GetUser
4. RemoveUser
5. CreateAccount
6. UpdateAccount
7. GetAccount
8. RemoveAccount

**Workgroup Management:**

Assumptions:
- Each workgroup member has a Baseline Identity

1.     RequestWorkGroup
2.	CreateWorkGroup
3.	RegisterWorkgroup
4.	GetRegisteredWorkgroup
5.	RequestUpdateWorkgroup
6.	UpdateWorkgroup
7.	RemoveWorkgroup
8.     RequestJoinWorkgroup
9.     AddToWorkgroup
10.   RemoveFromWorkgroup
11.   CreateWorkgroupAdmin
12.   UpdateWorkgroupAdmin

**Workflow Management:**

Assumptions:
- There is a defined workflow with worksteps and an initial commercial state

1. CreateWorkflow
2. UpdateWorkflow
3. RemoveWorkflow
4. GetWorkflow
5. CreateWorkflowstep
6. UpdateWorkflowstep
7. RemoveWorkflowstep
8. GetWorkflowStep
9. InitiateWorkflowInstance
10. PauseWorkflowInstance
11. ResumeWorkflowInstance
12. CloseWorkflowInstance

Execution Framework (EF) Management:

Assumptions:
- ???

1. DefineEF
2. CreateEF
3. UpdateEF
4. RemoveEF
5. GetEF
6. InitiateEF
7. PauseEF
8. ResumeEF

Operations Management:

Assumptions:
- ...

1. SubmitTransaction
2. UpdateTransaction
3. RemoveTransaction
4. GetTransaction
5. GetWorkflowInstanceState
6. GetWorkflowInstanceHistory
7. TokenizeWorkflowInstanceState
8. UpdateToken
9. TransferToken
10. PartialExitBaseline
11. FullExitBaseline
12. ImportBaselineState
13. ChangePubKeyforAccount
14. TransferTokenToNew

** Baseline Smart Contract Management & Operations **
1. DeployBaselineContracts
2. StartUpdateBaselineContracts
3. CancelUpdateBaselineContracts
4. PauseBaselineProcessing
5. ResumeBaselineProcessing
6. SubmitBatchToL1
7. VerifyBatchOnL1
8. CreateBatchCommittment
9. RegisterContractAdmin
10. UpdateContractAdmin

Probably missed a whole bunch but this is probably a good start.

**Comment by Consianimis** [comment]
@Therecanbeonlyone1969 - This is great, thank you !

**Comment by Consianimis** [comment]
Added to Baseline Protocol - Requirements Mastersheet. Issue can be closed.
