### ISSUE TITLE
ZK Service hardening

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#24]
One of the key things that needs to be spiked, articulated and executed is the specific roadmap that leads to a production-ready zk service. What should "production ready" mean in this context? What needs to happen to get there? Who needs to do the work. And what's blocking them that we can help them overcome.

**Comment by humbitious** [comment]
One of the key things that needs to be spiked, articulated and executed is the specific roadmap that leads to a production-ready zk service.  What should "production ready" mean in this context? What needs to happen to get there? Who needs to do the work. And what's blocking them that we can help them overcome.

**Comment by humbitious** [comment]
@skarred14 @kthomas I know we had a bit of a breakthrough with ZK work this last week. How does that work sync with this Epic?  Might be worth doing a summit with all the ZK experts in the next couple weeks and organize some target milestones.

**Comment by gleim** [comment]
The work performed with the benchmarker in https://github.com/ethereum-oasis/baseline/issues/139 [and the associated whitepaper write-up to be published soon] indicate that the simplicity of the initial Baseline circuits introduces little to no threat to the production-readiness of a system solution including the initial Baseline circuits.  Further, the benchmarker associated with Issue #139 can be applied to future circuits of equal or greater complexity.  This issue can be closed pending the creation and publication of additional Baseline business logic circuits of greater complexity.
