### ISSUE TITLE
MSFT Dynamics Integration Kit

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#34]

**Comment by humbitious** [comment]
@danielnorkin and Envision report that this epic can be closed. An integration kit for Dynamics now is on the MSFT app store [here](https://appsource.microsoft.com/en-us/product/dynamics-365-for-finance-and-operations/envision_blockchain-5199407.dynamics365-radish34)

**Comment by danielnorkin** [comment]
Correct. The parameter screen in the plugin you linked to above, allows for
native integrations. No user should need to go outside of their Dynamics
Environment to know if something is "baselined."
