### ISSUE TITLE
ZK-Circuit Libraries

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#37]

**Comment by humbitious** [comment]
@hadasz @gleim @skarred14 is this epic redundant?

**Comment by gleim** [comment]
The answer depends on the definition/description of the Issue (as the Issue Title can be interpreted multiple ways).

**Comment by gleim** [comment]
Closing out immediate rounds of ZKP circuit library work captured in benchmarker initiative.
