### ISSUE TITLE
May/June PR on New Members

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#4]
This is a project with the goal of announcing significant new public support for and participation in the baseline protocol initiative. Requires a concerted and coordinated effort to compile the list of companies joining the ranks of contributors and to work with some of the larger companies that will want help to navigate announcing public support.

**Comment by akraft-cc** [comment]
### Streamlining Engagement *Updated*
Create a section for immediate clarification and engagement of visitors, including a short video, access to key information, and a link to the repo. This is basically similar to the current website format, but with video content as one of the three immediate "actionable" boxes.

<img width="1028" alt="Screen Shot 2020-04-27 at 4 53 26 PM" src="https://user-images.githubusercontent.com/64434821/80420813-62ffc000-88a9-11ea-9590-a2a79811693a.png">

**Comment by akraft-cc** [comment]
### Getting Involved Pipeline
It seems like there are a lot of discussion channels on the website, but to a new visitor it might not be clear where the best place to start is (in terms of the most up-to-date or directly engaging content). It might be worth splitting this part into two actionable sections: 
1. **Join the Discussion** (active)
2. **Stay Informed** (passive)

This creates three possible options for new users: Active engagement/Passive engagement/Active & Passive engagement. Based on who joins what channels, we can better meet the needs of everyone interested in the project while still making information flow available to all without restriction.

<img width="1004" alt="Screen Shot 2020-04-27 at 5 01 00 PM" src="https://user-images.githubusercontent.com/64434821/80421219-1f598600-88aa-11ea-96b0-6b1e79d71b2a.png">

**Comment by akraft-cc** [comment]
### Addressing Business Applications & Examples
In order to clarify what Baseline is, it might be worth including a section with text directly pulled from https://docs.baseline-protocol.org/baselining/your-product and highlighting "Business Use Cases" on the front page of the website. 

<img width="1016" alt="Screen Shot 2020-04-27 at 5 21 47 PM" src="https://user-images.githubusercontent.com/64434821/80422127-99d6d580-88ab-11ea-806a-54dd774913f7.png">

**Comment by chtmorris** [comment]
@humbitious who is keeping track of this? Is there a Google sheet somewhere?
