### ISSUE TITLE
Corporate Identity

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#49]
This is the container epic for work involving corporate identity efforts. In the context of the Baseline Protocol, identity specifically means: Companies and other parties in a baseline workgroup, sending messages and sharing baseline proofs, need to know with certainty that the other parties in that workgroup are the actual parties they think they are, that those parties have authorized interacting in that workgroup, and that the messaging endpoints and on-chain accounts are correct (and correctly matched...meaning that you wouldn't want to accidentally send private date via p2p message to a different counterparty than the one with the associated eth account sharing a particular baseline proof). 

It is expected that the Baseline Protocol is a consumer of Corporate Identity techniques, not a locus of R&D on the subject. The DID standard is expected to be supported. Other standards, techniques and services may also be supported.

One related topic that may be contained in this overall Identity epic is how the "corporate ID" (possibly "org id") of a counterparty allows implementations behind the primary ID for managing users, permissioning, tracking.  For example, a corp administrator may set up a gas service for the organization and then use a dashboard to track which users are expending gas. This dashboard would bridge the organization's LDAP or Active directory to handle the internal tracking and permissioning of users without requiring the cross-company baseline protocol itself to manage individual users.

**Comment by danielnorkin** [comment]
@bradleyjw @brantlymillegan - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.

**Comment by danielnorkin** [comment]
As per @bradleyjw @bradleyjw - closing this epic
