### ISSUE TITLE
Standing up for Mainnet Campaign

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#5]
Been thinking about how to put a big giant crack in the ever-thinning dam that prevents overt corporate support for appropriate uses of public Mainnet. 

Here is a strawman: campaign targeted at May/June where we write a strong statement of support for Mainnet that is carefully worded to be easy to put one's name on without risking getting shot in the back by corporate antibodies (word-smithing now). We use our networks to evangelize it and set up a site to let people easily list themselves and 'take a stand'.

Thinking of motivators to gamify this...spark a movement.

**Comment by danielnorkin** [comment]
You mean something like a pledge to achieve carbon net 0, but for Mainnet.

**Comment by Souptacular** [comment]
Things I feel like would go along very well with this:

- One page website that succinctly outlines what mainnet is and how to use it today (via Baseline).
- Video demonstration of Baseline that is under 3 minutes long (maybe even 1.5 minutes).
- A few (literally 1-3) links on good reading materials about moving to mainnet or dispelling rumors about mainnet.

**Comment by akraft-cc** [comment]
> Things I feel like would go along very well with this:
> 
> * One page website that succinctly outlines what mainnet is and how to use it today (via Baseline).
> * Video demonstration of Baseline that is under 3 minutes long (maybe even 1.5 minutes).
> * A few (literally 1-3) links on good reading materials about moving to mainnet or dispelling rumors about mainnet.

I really like this idea. I can help with a video demonstration... would we make that a simple explainer, or perhaps more individual-interview focused to show the range of potential use cases? 
Would love more thoughts on this.
