### ISSUE TITLE
Explore Baselining and IOT

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#53]

**Comment by johnmonarch** [comment]
I will identify a handful of IoT partners of ours that would want to contribute on the technology end

**Comment by dh6oodman** [comment]
Hello to both of you!

Vitro is a member of EEA and very interested to join your work in Baseline. We focus on IoT data authentication via low-cost local ECC hardware (encrypt, hash and sign at the point of origin) and Oracle input to smart contracts of deterministic operating data.

I would like to be a part of the contributing group and have registered to join the call on the 28th. Not sure the proper channels to interact .. so apologies for lurking/barging in.

**Comment by dh6oodman** [comment]
I would propose a higher order view of IoT .. less from edge application perspective and more from the IoT <> blockchain point of view. Vitro builds edge and gateway hardware with autonomous ECC authentication. Assuming that the edge device can interface with local hardware (NFC, RFID, PMBus, etc.), the data can be rendered into IoT Blocks. IoT Blocks are encrypted, hashed and signed at to point of origin per a sampling interval. IoT Blocks are secret and secure in transit and at rest. We have a functioning oracle that can respond to requests for IoT datasets: the oracle authenticates the IoT Block data and provides the decrypted payload to the calling on-chain process.

Applications listed above are all possible with local interface to equipment .. but from the perspective of Baseline, trusted IoT data served to on-chain processes would be a tangible step forward at a general level. We would welcome a role in making that happen.

**Comment by humbitious** [comment]
Right on, @dh6oodman and @johnmonarch. I can bring this up on Monday's SSC as a project call.  Yes?  @dh6oodman -- if you aren't on the invite list for the SSC calls, send my via slack or email your email address and I'll add you.
