### ISSUE TITLE
Website Evolution

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#6]
This is a container Epic for specific and iterative efforts to continuously improve and modify the website (https://baseline-protocol.org) to serve the community as it grows and evolves.  People accountable for this project can add Epics and tasks for this as children of this Epic to roll everything up to the dashboard.

**Comment by akraft-cc** [comment]
### Streamlining Engagement _Updated_
Create a section for immediate clarification and engagement of visitors, including a short video, access to key information, and a link to the repo. This is basically similar to the current website format, but with video content as one of the three immediate "actionable" boxes.

We could also include content that @Souptacular suggested, including a one pager that succinctly outlines what mainnet is and how to use it today (via Baseline) and links on good reading materials about moving to mainnet or dispelling rumors.

<img width="1028" alt="Screen Shot 2020-04-27 at 4 53 26 PM" src="https://user-images.githubusercontent.com/64434821/80422471-35684600-88ac-11ea-9653-2fb0c995515d.png">

**Comment by akraft-cc** [comment]
### Getting Involved Pipeline
It seems like there are a lot of discussion channels on the website, but to a new visitor it might not be clear where the best place to start is (in terms of the most up-to-date or directly engaging content). It might be worth splitting this part into two actionable sections:
1. Join the Discussion (active)
2. Stay Informed (passive)

This creates three possible options for new users: Active engagement/Passive engagement/Active & Passive engagement. Based on who joins what channels, we can better meet the needs of everyone interested in the project while still making information flow available to all without restriction.

<img width="1004" alt="Screen Shot 2020-04-27 at 5 01 00 PM" src="https://user-images.githubusercontent.com/64434821/80422545-592b8c00-88ac-11ea-906e-9161bb22b659.png">

**Comment by akraft-cc** [comment]
### Addressing Business Applications & Examples
In order to clarify what Baseline is, it might be worth including a section with text directly pulled from https://docs.baseline-protocol.org/baselining/your-product and highlighting "Business Use Cases" on the front page of the website.

<img width="1016" alt="Screen Shot 2020-04-27 at 5 21 47 PM" src="https://user-images.githubusercontent.com/64434821/80422579-6b0d2f00-88ac-11ea-8dd4-bd8c3f825159.png">

**Comment by humbitious** [comment]
This is great stuff, and I love how @akraft-cc and @tjchmielewski work aligns. Would be great to do a 5min retrospective on this and see where we might go next during the SSC Meeting on the 4th or 10th of May.
