### ISSUE TITLE
SSC Agenda and Minutes: June 8, 2020

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#81]
Agenda:

[5min]: Welcome new attendees, request for additions/modifications to agenda.

[10min]: Celebrate momentum -- SAP/Dynamics + Upcoming New Demo + Growth metrics + Init-Core branch progress and implications + reconfirm Invoice-tokenization Epic for Summer

[15min]: Walk-through current epics on roadmap, highlight "shiny objects"

[20min]:  Featured new projects -- Gas station [@breakpointer ], Docusign-integration [@kthomas ], Oracle Data Integration [Chainlink], zkp benchmarker [@hadasz]

[5min]: OASIS and hackathon fund-drive

[5min]: Updating member lists

SSC Meetings Recorded and posted for public on [Baseline Protocol YouTube Channel](https://www.youtube.com/playlist?list=PLxmhMSa49Q1CVwTdcUNeoqoME6GRwtSTA)

**Comment by gleim** [comment]
zkp benchmarker analysis of ZKP DSLs zokrates & pequin including consideration of different types and complexities of circuits + future work + relevance to Baseline

**Comment by humbitious** [comment]
Minutes from the June 8 SSC Meeting, recording here: https://youtu.be/ZnezTe5ooFA

~40 people on call (recording didn't indicate, and missed taking a count during call)

1) Reviewed the new agendas and minutes 

2) Peter Kris (BlockUnison) introduced himself and mentioned that they want to do a project on integrating Mulesoft.

3) Christian Schmiedel (Fraunhofer Institute) introduced himself and Myron -- manufacturing research...working on a baseline protocol demo.

4) Amir Razi (Real E Chain) focused on doing baseline education for the public.

5) Johann Eid (Chainlink) introduced himself..see below for project details.

6) Jesse Shia (AgilePoint) introduced himself, discussed B2B process automation.

7) Vijay Michalik (ConsenSys PegaSys) introduced himself and encouraged baseliners to engage him on helping projects with infrastructure (mainnet node, orchestration).

8) A discussion of successful releases ensued (Dynamics/SAP Press Release).

9) Chair instructed SSC members on how to authorize being listed on the public [list](https://docs.baseline-protocol.org/community/community-leaders) and previewed the upcoming TSC elections to be held in September. Important: if you want to vote for TSC member, you must have submitted something to the /baseline repo and had it merged to master. Even a spellcheck counts, but if you haven't contributed something that was merged to the master branch, you can't vote.

10) A discussion of the Google Sheets / MSFT Dynamics project ([released on June 9](https://www.einpresswire.com/article/519009730/baseline-protocol-initiative-integrates-google-sheets-and-microsoft-dynamics-365-using-public-ethereum-blockchain)) ensued. 

11) Discussion of the "big tent pole project" of the summer, Invoice Tokenization #17 ensued and continued at around min 40 of the video). Chair made call to get involved.

12) "Shiny Objects" Roadmap Review: Epics reviewed listed here (and discussion starts roughly at min 15 on the youtube video) [Chair reminded everyone that the /baseline-roadmap repo is where epics are placed whereas Issues and engineering work is in /baseline repo.  Issues should link up to roadmap epics, so we can track it.  @bitwiseguy did great work helping to streamline and clean this process up.]

-- #73 (generalized "consistency zk circuit" discussed)
-- Specifications work will begin in a few weeks.  (Still looking for an accountable person to lead)
-- Security work reviewed by @CannotContainMyself, committed to adding Epics
-- #63 reviewed by @bradleyjw 
-- #56 reviewed by @christianschmiedel: Baseline in Manufacturing..involves a machine tool and baselining that a product manufactured by the tool was done under the right conditions
-- #53 IOT @johnmonarch (still in early stage), committed to adding detail to Epic.
-- #47 @kthomas reviewed this upcoming Docusign Integration Kit, slated to drop to public in next few weeks.
-- #89 Created this epic for @JohannEid to contain the Chainlink demo to use data like weather or market data to deal with non-determinism in baseline workflow steps.
-- #17 @skarred14 leading (see discussion above)
-- #139 (in baseline repo) Benchmarking Pequin and Zokrates. Discussion with @hadasz ensued. Worth reviewing the data: (min 43 of video). Important for estimating unit costs for baseline activities on chain
-- #41 @breakpointer discussed upcoming ConsenSys/Infura project on providing Gas and what needs to happen on the open source side to make it work.

13) @kthomas reported that NATS integration will be in the upcoming Init-Core merge, which will give one option for the messaging protocol.

14) Monthly/quarterly "hackfest" to do real engineering syncing and project help proposed.

15) Chair advised team to seek out OASIS Carol Geyer to become a Sponsor of Ethereum-Oasis and reported on progress toward a method of "tin cupping" funds for items like bounties and hackathons. 

16) Discussion of encouraging senior executives to make clear statement on appropriate use of Mainnet in business ensued with @chtmorris:  [“We permit our employees to consider uses of the Mainnet and public blockchain networks. We contribute and adhere to strict standards of appropriate use and security, so that we can confidently employ the Mainnet in production — when it is the right tool for the job.”](https://medium.com/@jwolpert/a-common-sense-statement-on-blockchain-and-the-business-mainnet-10077d969ab1)

Adjourned [59mins].
