### ISSUE TITLE
SSC Agenda and Minutes: July 20, 2020

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#84]
Agenda:

[5min]: Welcome new attendees, request for additions/modifications to agenda.

[5min]: Review minutes and actions from July 6 : #83 and interlock on key TSC items from #77

[5min]: Celebrate momentum -- Recent announcements + Growth metrics 

[20min]:  Featured projects status

[15min]: Walk-through new and current epics on [roadmap](https://app.zenhub.com/workspaces/baseline-main-roadmap-5ea5f5066d554d046aa369bd/board?repos=258320699), highlight "shiny objects"

[5min]: Follow-through on focus meetings/hacks/summits.

[5min]: Regular business

SSC Meetings Recorded and posted for public on [Baseline Protocol YouTube Channel](https://www.youtube.com/playlist?list=PLxmhMSa49Q1CVwTdcUNeoqoME6GRwtSTA)

**Comment by Rudolphus** [comment]
Greetings @humbitious we had contact on twitter about:

Creating a epic
"Baseline solution that engineers always have the right and newest construction drawing on the cloud and not make the fault to select a older one for taking with them in the field"

Putting a team together of people familair in the industry working with developers to create a
solution for: Autodesk /Autocad / Fusion 360 / Revit / AEC

Problem technical drawings are now often put on the cloud by hand and engineers working with the drawings have a big chance they select the wrong and old revision drawing  in to the field and enlarge construction errors.

**Comment by sambacha** [comment]
Would like to add an EPIC in the same vain as the current EDI one but with XML/defined XSD and an authenticated Non repudiation chain digest for facilitating B2B messaging

**Comment by humbitious** [comment]
Let's talk about this on the SSC call. 

> Greetings @humbitious we had contact on twitter about:
> 
> Creating a epic
> "Baseline solution that engineers always have the right and newest construction drawing on the cloud and not make the fault to select a older one for taking with them in the field"
> 
> Putting a team together of people familair in the industry working with developers to create a
> solution for: Autodesk /Autocad / Fusion 360 / Revit / AEC
> 
> Problem technical drawings are now often put on the cloud by hand and engineers working with the drawings have a big chance they select the wrong and old revision drawing in to the field and enlarge construction errors.

https://github.com/ethereum-oasis/baseline/issues/183

**Comment by hackneycrypto** [comment]
> Greetings @humbitious we had contact on twitter about:
> 
> Creating a epic
> "Baseline solution that engineers always have the right and newest construction drawing on the cloud and not make the fault to select a older one for taking with them in the field"
> 
> Putting a team together of people familair in the industry working with developers to create a
> solution for: Autodesk /Autocad / Fusion 360 / Revit / AEC
> 
> Problem technical drawings are now often put on the cloud by hand and engineers working with the drawings have a big chance they select the wrong and old revision drawing in to the field and enlarge construction errors.

I'm hoping to join the call today for the first time. I might be able to help with this epic. I'm involved with https://www.constructionblockchain.org/ and Autodesk are one of our partner organisations. We could also get Bentley Systems involved.

**Comment by juanfranblanco** [comment]
Quick note: The the technical drawing revisions, do not need to be only for construction, other examples are collaboration on engineering, land division / registry approval.

**Comment by Therecanbeonlyone1969** [comment]
Announcing an effort to redesign the current Baseline smart contracts to
a) allow for L2 scaling solutions
b) support extensible setup and circuits -- utilizing PLONK, a new SNORK
c) support multiple workgroups through the introduction of proxy  contracts
 by adapting the current zksynch implementation from Mattr Labs https://github.com/matter-labs/zksync/blob/master/docs/protocol.md

Looking for collaborators on this effort.

@humbitious @kt

**Comment by humbitious** [comment]
# Minutes

35 attendees
![image](https://user-images.githubusercontent.com/1388686/88075871-5e187880-cb47-11ea-92bc-b0d48bed412f.png)


Minutes from #83 approved by loose consensus.

Teams introducing themselves: 
Google introduced: Lou Piscopo and Ryan Krebs. (min 7) 
Erick from Supply Chain Association of Canada.
Vitro -- IOT in energy sector.

@Rudolphus and Steve Smith presented project plans for baselining Autodesk and issues in the construction industry. (min 5) 

Jimmie Lentz from Duke University confirmed that several members engaging the grad students to work on projects.

@humbitious mentioned #89 and the recent announcements by Chainlink to work on that project, using Google BigQuery.  Video of Adelyn Zhou

Chair reminded attendees that voting period for the TSC is coming, and that only people who have committed code to the main branch can vote...so get those pull requests in. 

Discussion on the issues with using Gitbook ensued. See #77 for details on status. (min 15)  @jorydotcom looking at switching to docusaurus or readthedocs after init-core release.

Discussion of community growth (min 17)

Discussion of Init-Core release plans ensued. Current target for release as "Baseline Protocol v0.1". Current release date projected for week of August 9, 2020.  (Caveat: dates can change.)  *Call for help to review the Init-Core branch.* (min 18)

Demos #10 (baseline as a service) and #47 (docusign) will be enabled with Init-Core release.

Discussion of how baseline is about open standards development 

Discussion of MSFT project #98 slated for after Init-core. (min 98)

@hacera_jonathan discussion of #175 in /baseline repo. (min 29)

Further discussion of /baseline repo #183 and maintaining quality of engineering drawings. Also discussion with @yorkerhodes3 regarding the related project #55 (possibly #56)  (min 30)

@Therecanbeonlyone1969 discussed trusted execution environments. (min 35) 

Chair reminded committee to organize appropriate design/planning/development meetings and activities for their respective projects outside of the regular SSC/TSC meetings, which are multiple project review meetings.

@gleim discussed #12 and other projects in zero knowledge and healthcare. (min 39)

Projects currently building demos, components or integrations should keep an eye on the init-core branch of the /baseline repo and use that where possible, so that their work can stay ahead of changes coming in August.

Chair described how to create new master epics and provided the following video to help people walk through using the master epic/project template:  https://youtu.be/Hs-8GrYr7FU

Discussion about ZK frameworks and Plunk ensued with @Therecanbeonlyone1969 (min 48)

Discussion of upcoming EDI projects ensued. (min 52) 

Avia Kraft of CoreConvergence previewed upcoming community video project, to be reviewed next SSC Meeting.

An executive from Oracle.com will be interviewed on The Baseline show at noon on Wednesday 7/22 here: https://youtu.be/V2zK2gMgZc4  
Every week at Noon us-eastern on Wednesdays @kyleellicott will be interviewing a new person or company doing interesting work with the Mainnet.
