### ISSUE TITLE
Salesforce Integration 

### ISSUE THREAD

**Issue by domsteil** [ethereum-oasis/baseline-roadmap#96]
Extending the DappSuite Managed Package and open-source middleware to baseline Salesforce workflows and objects using the Ethereum Mainnet

- Baselined Salesforce RFP Process
- Baselined Salesforce MSA Process 

Working on initial demo of baselined RFP process from CRM system.

**Comment by domsteil** [comment]
I am working on initial updates to the [dappsuite middleware](https://github.com/dappsinc/dappsuite-middleware/blob/master/baseline/README.md). Will use the baseline npm packages when available. 

Main components for the demo will be callout and connector classes with the structured data from the Radish34 demo to connect with D365. 

Possible use case will be around baselining RFP process: 

Verify the same RFP to 5 different companies; baseline with buyer and the 5 suppliers

- baseline proof on mainnet
- generate a commit and get proof back
- then share the commit & proof with other system

Each sends back own private / their own version of the bid

each bid is bilateral 4 other are child.
none of the suppliers have any awareness at all.
each one is verifiable connected to the parent RFP.

Then segway of create agreement with line items into MSA process for the third workstep.

**Comment by domsteil** [comment]
Salesforce Integration Updates:

- DappSuite Solidity Compiler Controller has been updated to support Zokrates DSL using @baseline-protocol/privacy interface:

compile(source: string, location: string): Promise<any>;
computeWitness(artifacts: any, args: any[]): Promise<any>;
exportVerifier(verifyingKey): Promise<string>;
generateProof(circuit, witness, provingKey): Promise<string>;
setup(circuit): Promise<any>;

We are working on implementing the other core RPC methods from @baseline-protocol/api and the Callout from SFDC on a Standard Record.

**Comment by domsteil** [comment]
Salesforce Integration Updates:

- baseline core v0.1.0 npm packages installed to dappsuite-middleware
- API routes created on index.js for callouts from Salesforce
- Apex Wrappers for Protocol Message and Proposal 
- Apex Invocable Method Callout Classes created for Protocol Message to be used in Process Builder / Flow

We have started to implement Global Action with custom VFP to Baseline Records by Object and Record Id. We have also started on creating a Baseline Dashboard that shows Organizations, Workgroups, Circuits and Baselined Records.

First recorded demo of end to end flow of Baselining a Salesforce Standard Object will be done by this week.

**Comment by domsteil** [comment]
Salesforce Integration Updates:

- DappSuite Managed Package 1.9500 (Beta 1) is in Early Release (https://login.salesforce.com/packaging/installPackage.apexp?p0=04t1K000002qnJY)
- DappSuite Managed Package Custom Metadata Settings added to support Infura Managed Transaction Service
- [DappSuite Middleware has been updated with the Baseline Core npm Packages and Baseline JSON RPC Methods](https://github.com/dappsinc/dappsuite-middleware/blob/baseline/baseline.api.js) 
- Baseline Global Action Component (attached) has been created

![DappSuite Baseline Global Action Component](https://user-images.githubusercontent.com/5036652/96523628-0911fe80-122b-11eb-8d6b-7a763c2d6646.png)

We are aiming for a release of DappSuite 1.9500 with Baselining capabilities by the end of this month.

**Comment by domsteil** [comment]
Dappsuite with Baseline Protocol is now available on the Salesforce AppExchange: https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000EcqdXUAR

![dappsuite_appexchange](https://user-images.githubusercontent.com/5036652/98975528-125d5680-24cb-11eb-8007-0b06a47f06e6.png)

**Comment by danielnorkin** [comment]
@domsteil - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
